# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-08 18:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AutorizationRequest',
            new_name='AuthorizationRequest',
        ),
    ]
