# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-08 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization_management', '0003_auto_20181008_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorizationrequest',
            name='observations',
            field=models.TextField(blank=True, null=True),
        ),
    ]
