# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-08 22:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization_management', '0004_authorizationrequest_observations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authorizationrequest',
            old_name='autorized',
            new_name='authorized',
        ),
    ]
