# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 00:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0004_auto_20170803_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='validatecertificatedatarequest',
            name='status_text',
            field=models.CharField(default='n/d', max_length=256),
        ),
        migrations.AddField(
            model_name='validatedocumentdatarequest',
            name='status_text',
            field=models.CharField(default='n/d', max_length=256),
        ),
        migrations.AddField(
            model_name='validatepersoncertificatedatarequest',
            name='status_text',
            field=models.CharField(default='n/d', max_length=256),
        ),
        migrations.AddField(
            model_name='validatepersondocumentdatarequest',
            name='status_text',
            field=models.CharField(default='n/d', max_length=256),
        ),
    ]
