# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 03:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0005_auto_20170814_0002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='validatecertificatedatarequest',
            name='codigo_de_error',
        ),
    ]
