# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-21 00:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0006_remove_validatecertificatedatarequest_codigo_de_error'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='validatepersoncertificatedatarequest',
            name='codigo_de_error',
        ),
    ]
