# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-12 17:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0007_remove_validatepersoncertificatedatarequest_codigo_de_error'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validatecertificaterequest',
            name='data_request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='validator.ValidateCertificateDataRequest'),
        ),
        migrations.AlterField(
            model_name='validatedocumentrequest',
            name='data_request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='validator.ValidateDocumentDataRequest'),
        ),
        migrations.AlterField(
            model_name='validatepersoncertificaterequest',
            name='data_request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='validator.ValidatePersonCertificateDataRequest'),
        ),
        migrations.AlterField(
            model_name='validatepersoncertificaterequest',
            name='person',
            field=models.CharField(help_text='Identificación de la persona solicitante', max_length=50),
        ),
        migrations.AlterField(
            model_name='validatepersoncertificaterequest',
            name='public_certificate',
            field=models.TextField(help_text='Certificado público  de firma, para firma digital avanzada'),
        ),
        migrations.AlterField(
            model_name='validatepersondocumentrequest',
            name='data_request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='validator.ValidatePersonDocumentDataRequest'),
        ),
        migrations.AlterField(
            model_name='validatepersondocumentrequest',
            name='person',
            field=models.CharField(help_text='Identificación de la persona solicitante', max_length=50),
        ),
        migrations.AlterField(
            model_name='validatepersondocumentrequest',
            name='public_certificate',
            field=models.TextField(help_text='Certificado público  de firma, para firma digital avanzada'),
        ),
    ]
