# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-27 01:10
from __future__ import unicode_literals

from django.db import migrations
import institution.models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='public_certificate',
            field=institution.models.EncrytedText(),
        ),
        migrations.AlterField(
            model_name='institution',
            name='public_key',
            field=institution.models.EncrytedText(),
        ),
        migrations.AlterField(
            model_name='institution',
            name='server_public_key',
            field=institution.models.EncrytedText(),
        ),
        migrations.AlterField(
            model_name='institution',
            name='server_sign_key',
            field=institution.models.EncrytedText(),
        ),
    ]
