# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-03 00:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0002_auto_20171027_0110'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationurl',
            name='is_demo',
            field=models.BooleanField(default=False),
        ),
    ]
