# Generated by Django 3.1.2 on 2021-05-21 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0002_auto_20210408_0816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='validatedocumentdatarequest',
            name='code',
        ),
        migrations.RemoveField(
            model_name='validatedocumentdatarequest',
            name='errors',
        ),
        migrations.RemoveField(
            model_name='validatedocumentdatarequest',
            name='signers',
        ),
        migrations.RemoveField(
            model_name='validatedocumentdatarequest',
            name='warnings',
        ),
        migrations.AddField(
            model_name='validatedocumentdatarequest',
            name='validation_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
