# Generated by Django 3.1.11 on 2021-05-22 16:21

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0003_auto_20210521_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validatedocumentdatarequest',
            name='validation_data',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
    ]
