# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-16 00:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0004_auto_20171115_2025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='validatedocumentrequest',
            name='format',
        ),
        migrations.AddField(
            model_name='validatedocumentdatarequest',
            name='format',
            field=models.CharField(choices=[('cofirma', 'CoFirma'), ('contrafirma', 'ContraFirma'), ('msoffice', 'MS Office'), ('odf', 'Open Document Format')], default='n/d', max_length=15),
        ),
    ]
