# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-16 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0006_auto_20180403_0558'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='email',
            field=models.EmailField(default='demo@dfva.info', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='institution',
            name='phone',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
