# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-15 05:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0014_auto_20181103_0101'),
    ]

    operations = [
        migrations.AddField(
            model_name='authenticatedatarequest',
            name='hash_docsigned',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='authenticatedatarequest',
            name='resume',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='signdatarequest',
            name='hash_docsigned',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='signdatarequest',
            name='resume',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
