# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 00:44
from __future__ import unicode_literals

import corebase.presentation
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('name', models.CharField(max_length=250)),
                ('code', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('domain', models.CharField(max_length=250)),
                ('institution_unit', models.CharField(default='ND', max_length=250)),
                ('private_key', models.TextField()),
                ('public_key', models.TextField()),
                ('public_certificate', models.TextField()),
                ('server_sign_key', models.TextField()),
                ('server_public_key', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('view_institution', 'Can see available tasks'),),
                'ordering': ('pk',),
            },
            bases=(models.Model, corebase.presentation.PEMpresentation),
        ),
        migrations.CreateModel(
            name='NotificationURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250)),
                ('url', models.URLField()),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corebase.Institution')),
            ],
            options={
                'permissions': (('view_notificationurl', 'Can see available notification urls'),),
                'ordering': ('institution',),
            },
        ),
    ]
