# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-18 22:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('corebase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserConditionsAndTerms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('document_signed', models.TextField()),
                ('signed', models.BooleanField(default=False)),
                ('organization', models.CharField(max_length=100)),
                ('organization_unit', models.CharField(max_length=100)),
                ('use_reason', models.TextField(help_text='¿Porqué nosotros deberíamos permitirle usar el servicio de firma?')),
                ('phone', models.CharField(max_length=25)),
                ('contact_email', models.EmailField(max_length=254)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
