# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 01:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corebase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationurl',
            name='not_webapp',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notificationurl',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
