# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-10 03:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corebase', '0002_userconditionsandterms'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification_number', models.CharField(max_length=25)),
                ('signature_date', models.DateField()),
                ('full_name', models.CharField(max_length=25)),
            ],
        ),
        migrations.RenameModel(
            old_name='ErrorEncontrado',
            new_name='ErrorFound',
        ),
        migrations.RenameModel(
            old_name='Advertencia',
            new_name='WarningReceived',
        ),
        migrations.RenameField(
            model_name='basedocument',
            old_name='errores',
            new_name='errors',
        ),
        migrations.RenameField(
            model_name='basedocument',
            old_name='advertencias',
            new_name='warnings',
        ),
        migrations.RenameField(
            model_name='errorfound',
            old_name='codigo',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='errorfound',
            old_name='detalle',
            new_name='detail',
        ),
        migrations.RenameField(
            model_name='warningreceived',
            old_name='descripcion',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='basedocument',
            name='firmantes',
        ),
        migrations.DeleteModel(
            name='Firmante',
        ),
        migrations.AddField(
            model_name='basedocument',
            name='signers',
            field=models.ManyToManyField(to='corebase.Signer'),
        ),
    ]
