# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 05:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corebase', '0002_auto_20170719_0115'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='bccr_bussiness',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='institution',
            name='bccr_entity',
            field=models.IntegerField(default=1),
        ),
    ]
