# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 03:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('corebase', '0003_auto_20170719_0547'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('identification', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
