# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 23:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corebase', '0005_auto_20170803_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='cipher_token',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='personlogin',
            name='code',
            field=models.TextField(),
        ),
    ]
