# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-13 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corebase', '0006_auto_20170803_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='cipher_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
