# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-15 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='institution_unit',
            field=models.CharField(default='ND', max_length=250),
        ),
    ]
