# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 02:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authenticaterequest',
            name='expiration_datetime',
        ),
        migrations.AddField(
            model_name='authenticatedatarequest',
            name='expiration_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
