# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 05:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authenticatedatarequest',
            name='id_transaction',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='authenticatedatarequest',
            name='code',
            field=models.CharField(default='N/D', max_length=20),
        ),
    ]
