# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0002_institution_institution_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='authenticate_request',
            name='institution',
            field=models.CharField(default='nd', help_text='UUID de Institutión', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='authenticate_request',
            name='algorithm',
            field=models.CharField(choices=[('sha256', 'sha256'), ('sha384', 'sha384'), ('sha512', 'sha512')], help_text='\n    Debe ser alguno de estos : sha256, sha384, sha512\n    ', max_length=7),
        ),
        migrations.AlterField(
            model_name='authenticate_request',
            name='data_hash',
            field=models.CharField(help_text='Suma hash de data tamaño máximo 130 caracteres, usando el algoritmo especificado ', max_length=130),
        ),
        migrations.AlterField(
            model_name='authenticate_request',
            name='public_certificate',
            field=models.TextField(help_text='Certificado público de la institución (ver Institución) '),
        ),
    ]
