# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 13:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0003_auto_20170418_0232'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authenticatedatarequest',
            options={'ordering': ('request_datetime',), 'permissions': (('view_authenticatedatarequest', 'Can see available Authenticate Data Request'),)},
        ),
        migrations.AlterModelOptions(
            name='authenticaterequest',
            options={'ordering': ('arrived_time',), 'permissions': (('view_authenticaterequest', 'Can see available Authenticate Request'),)},
        ),
        migrations.AlterModelOptions(
            name='institution',
            options={'ordering': ('pk',), 'permissions': (('view_institution', 'Can see available tasks'),)},
        ),
        migrations.AlterModelOptions(
            name='notificationurl',
            options={'ordering': ('institution',), 'permissions': (('view_notificationurl', 'Can see available notification urls'),)},
        ),
    ]
