# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 00:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0003_authenticatedatarequest_received_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authenticatedatarequest',
            name='name',
        ),
        migrations.AddField(
            model_name='authenticatedatarequest',
            name='sign_document',
            field=models.TextField(blank=True, null=True),
        ),
    ]
