# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-13 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0005_authenticatepersondatarequest_authenticatepersonrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='authenticatedatarequest',
            name='duration',
            field=models.SmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='authenticatedatarequest',
            name='status_text',
            field=models.CharField(default='n/d', max_length=256),
        ),
        migrations.AddField(
            model_name='authenticatepersondatarequest',
            name='duration',
            field=models.SmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='authenticatepersondatarequest',
            name='status_text',
            field=models.CharField(default='n/d', max_length=256),
        ),
    ]
