# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-12 17:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0006_auto_20170813_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authenticatepersonrequest',
            name='data_request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authenticator.AuthenticatePersonDataRequest'),
        ),
        migrations.AlterField(
            model_name='authenticaterequest',
            name='data_request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authenticator.AuthenticateDataRequest'),
        ),
    ]
