#!/bin/bash

NAME="dfva_app"                                  # Name of the application
DJANGODIR=/home/dfva/dfva/             # Django project directory
SOCKFILE=/home/dfva/gunicorn.sock  # we will communicte using this unix socket
USER=dfva                                        # the user to run as
GROUP=webapps                                     # the group to run as
NUM_WORKERS=3                                     # how many worker processes should Gunicorn spawn
DJANGO_SETTINGS_MODULE=dfva.settings             # which settings file should Django use
DJANGO_WSGI_MODULE=dfva.wsgi                     # WSGI module name

echo "Starting $NAME as `whoami`"

# Activate the virtual environment
cd $DJANGODIR
source /home/dfva/environment/bin/activate
export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
export PYTHONPATH=$DJANGODIR:$PYTHONPATH

# Create the run directory if it doesn't exist
RUNDIR=$(dirname $SOCKFILE)
test -d $RUNDIR || mkdir -p $RUNDIR

# Start your Django Unicorn
# Programs meant to be run under supervisor should not daemonize themselves (do not use --daemon)
exec /home/dfva/environment/bin/gunicorn ${DJANGO_WSGI_MODULE}:application \
  --name $NAME  --timeout 180 \
  --workers $NUM_WORKERS \
  --user=$USER --group=$GROUP \
  --bind=unix:$SOCKFILE \
  --log-level=info \
  --log-file=-
