defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
      [[entryPoints.https.tls.certificates]]
      certFile = "/certs/ucrbccr.core.ucr.ac.cr.cert"
      keyFile = "/certs/ucrbccr.core.ucr.ac.cr.key"
      [[entryPoints.https.tls.certificates]]
      certFile = "/certs/firmadigital-dev.ucr.ac.cr.cert"
      keyFile = "/certs/firmadigital-dev.ucr.ac.cr.key"
      [[entryPoints.https.tls.certificates]]
      certFile = "/certs/pki-dbmanager.ucr.ac.cr.cert"
      keyFile = "/certs/pki-dbmanager.ucr.ac.cr.key"

