# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 03:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signdatarequest',
            name='received_notification',
            field=models.BooleanField(default=False),
        ),
    ]
