# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 23:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signer', '0003_signpersondatarequest_signpersonrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signpersondatarequest',
            old_name='institution',
            new_name='person',
        ),
    ]
