# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-13 23:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signer', '0004_auto_20170802_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='signdatarequest',
            name='duration',
            field=models.SmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='signdatarequest',
            name='status_text',
            field=models.CharField(default='n/d', max_length=256),
        ),
        migrations.AddField(
            model_name='signpersondatarequest',
            name='duration',
            field=models.SmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='signpersondatarequest',
            name='status_text',
            field=models.CharField(default='n/d', max_length=256),
        ),
    ]
