# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-12 17:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signer', '0005_auto_20170813_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signpersonrequest',
            name='data_request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='signer.SignPersonDataRequest'),
        ),
        migrations.AlterField(
            model_name='signpersonrequest',
            name='public_certificate',
            field=models.TextField(help_text='Certificado público  de firma, para firma digital avanzada'),
        ),
        migrations.AlterField(
            model_name='signrequest',
            name='data_request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='signer.SignDataRequest'),
        ),
    ]
