# Generated by Django 3.0.7 on 2020-06-08 22:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserConditionsAndTerms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Texto')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Registered date')),
                ('document_signed', models.TextField(verbose_name='Document signed')),
                ('signed', models.BooleanField(default=False, verbose_name='Is signed?')),
                ('organization', models.CharField(max_length=100, verbose_name='Organization')),
                ('organization_unit', models.CharField(max_length=100, verbose_name='Organization Unit')),
                ('use_reason', models.TextField(help_text='Why we have to allow you to use this digital         signer service?', verbose_name='Use Reason')),
                ('phone', models.CharField(max_length=25, verbose_name='Phone')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='Contact Email')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AuthorizationRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('last_modification', models.DateTimeField(auto_now=True)),
                ('authorized', models.BooleanField(default=False)),
                ('finished', models.BooleanField(default=False)),
                ('observations', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('who_authorized', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='who_authorized', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Authorization request',
                'verbose_name_plural': 'Authorizations request',
            },
        ),
    ]
