# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-01 21:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorizationRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('last_modification', models.DateTimeField(auto_now=True)),
                ('authorized', models.BooleanField(default=False)),
                ('finished', models.BooleanField(default=False)),
                ('observations', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('who_authorized', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='who_authorized', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Authorizations request',
                'verbose_name': 'Authorization request',
            },
        ),
        migrations.CreateModel(
            name='UserConditionsAndTerms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('document_signed', models.TextField()),
                ('signed', models.BooleanField(default=False)),
                ('organization', models.CharField(max_length=100)),
                ('organization_unit', models.CharField(max_length=100)),
                ('use_reason', models.TextField(help_text='Why we have to allow you to use this digital         signer service?')),
                ('phone', models.CharField(max_length=25)),
                ('contact_email', models.EmailField(max_length=254)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
