# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-08 20:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authorization_management', '0002_auto_20181008_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorizationrequest',
            name='finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='authorizationrequest',
            name='who_authorized',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='who_authorized', to=settings.AUTH_USER_MODEL),
        ),
    ]
