# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-13 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='validatepersondocumentrequest',
            name='fin_vigencia',
        ),
        migrations.RemoveField(
            model_name='validatepersondocumentrequest',
            name='fue_exitosa',
        ),
        migrations.RemoveField(
            model_name='validatepersondocumentrequest',
            name='inicio_vigencia',
        ),
        migrations.RemoveField(
            model_name='validatepersondocumentrequest',
            name='nombre_completo',
        ),
        migrations.AddField(
            model_name='validatepersoncertificatedatarequest',
            name='fin_vigencia',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='validatepersoncertificatedatarequest',
            name='fue_exitosa',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='validatepersoncertificatedatarequest',
            name='inicio_vigencia',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='validatepersoncertificatedatarequest',
            name='nombre_completo',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
