# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-17 03:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0005_auto_20180403_0558'),
    ]

    operations = [
        migrations.RenameField(
            model_name='validatepersoncertificatedatarequest',
            old_name='fin_vigencia',
            new_name='end_validity',
        ),
        migrations.RenameField(
            model_name='validatepersoncertificatedatarequest',
            old_name='nombre_completo',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='validatepersoncertificatedatarequest',
            old_name='inicio_vigencia',
            new_name='start_validity',
        ),
        migrations.RenameField(
            model_name='validatepersoncertificatedatarequest',
            old_name='fue_exitosa',
            new_name='was_successfully',
        ),
        migrations.RenameField(
            model_name='validatepersondocumentdatarequest',
            old_name='fue_exitosa',
            new_name='was_successfully',
        ),
        migrations.AlterField(
            model_name='authenticatepersonrequest',
            name='algorithm',
            field=models.CharField(choices=[('sha256', 'sha256'), ('sha384', 'sha384'), ('sha512', 'sha512')], help_text='Debe ser alguno de los siguientes: sha256, sha384, sha512', max_length=7),
        ),
        migrations.AlterField(
            model_name='signpersonrequest',
            name='algorithm',
            field=models.CharField(choices=[('sha256', 'sha256'), ('sha384', 'sha384'), ('sha512', 'sha512')], help_text='Debe ser alguno de los siguientes: sha256, sha384, sha512', max_length=7),
        ),
        migrations.AlterField(
            model_name='validatepersoncertificaterequest',
            name='algorithm',
            field=models.CharField(choices=[('sha256', 'sha256'), ('sha384', 'sha384'), ('sha512', 'sha512')], help_text='Debe ser alguno de los siguientes: sha256, sha384, sha512', max_length=7),
        ),
        migrations.AlterField(
            model_name='validatepersondocumentrequest',
            name='algorithm',
            field=models.CharField(choices=[('sha256', 'sha256'), ('sha384', 'sha384'), ('sha512', 'sha512')], help_text='Debe ser alguno de los siguientes: sha256, sha384, sha512', max_length=7),
        ),
    ]
