# Generated by Django 3.0.7 on 2020-06-08 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BCCR_Monitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medition_time', models.DateTimeField()),
                ('authenticate', models.BooleanField(default=False)),
                ('signer', models.BooleanField(default=False)),
                ('validate_certificate', models.BooleanField(default=False)),
                ('validate_document', models.BooleanField(default=False)),
                ('everything_ok', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Monitor de servicios del BCCR',
                'verbose_name_plural': 'Estado de servicios del BCCR',
            },
        ),
        migrations.CreateModel(
            name='ErrorFound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=250)),
                ('detail', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Signer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification_number', models.CharField(max_length=25)),
                ('signature_date', models.DateField()),
                ('full_name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='System_Request_Metric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_bccr_call', models.DateTimeField(null=True)),
                ('end_bccr_call', models.DateTimeField(null=True)),
                ('start_save_database', models.DateTimeField(null=True)),
                ('end_save_database', models.DateTimeField(null=True)),
                ('transaction_status', models.IntegerField(null=True)),
                ('transaction_status_text', models.CharField(max_length=350, null=True)),
                ('transaction_success', models.BooleanField(default=False)),
                ('start_check_institution_certificate', models.DateTimeField(null=True)),
                ('end_check_institution_certificate', models.DateTimeField(null=True)),
                ('start_decrypt', models.DateTimeField(null=True)),
                ('end_decrypt', models.DateTimeField(null=True)),
                ('start_encryption', models.DateTimeField(null=True)),
                ('end_encryption', models.DateTimeField(null=True)),
                ('start_hashsum', models.DateTimeField(null=True)),
                ('end_hashsum', models.DateTimeField(null=True)),
                ('operation_type', models.CharField(max_length=30, null=True)),
                ('bccr_call', models.FloatField(default=0)),
                ('save_database', models.FloatField(default=0)),
                ('check_institution_certificate', models.FloatField(default=0)),
                ('decrypt_time', models.FloatField(default=0)),
                ('encrypt_time', models.FloatField(default=0)),
                ('total_spend_time', models.FloatField(default=0)),
                ('request_size', models.FloatField(default=0)),
            ],
            options={
                'verbose_name': 'Métrica del sistema',
                'verbose_name_plural': 'Métricas del sistema',
            },
        ),
        migrations.CreateModel(
            name='WarningReceived',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=512)),
            ],
        ),
    ]
