# Generated by Django 3.0.7 on 2020-06-09 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corebase', '0002_system_request_metric_institution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system_request_metric',
            name='institution',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
