# Generated by Django 3.1.2 on 2021-04-08 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0001_initial'),
        ('corebase', '0003_auto_20200609_0020'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now=True)),
                ('month', models.CharField(max_length=20)),
                ('year', models.CharField(max_length=20)),
                ('total_number_of_records', models.IntegerField()),
                ('authentication_total', models.FloatField(default=0)),
                ('signer_total', models.FloatField(default=0)),
                ('validatecertificate_total', models.FloatField(default=0)),
                ('validatedocument_total', models.FloatField(default=0)),
                ('authentication_total_spend_time', models.FloatField(default=0)),
                ('signer_total_spend_time', models.FloatField(default=0)),
                ('validatecertificate_total_spend_time', models.FloatField(default=0)),
                ('validatedocument_total_spend_time', models.FloatField(default=0)),
                ('authentication_request_size', models.FloatField(default=0)),
                ('signer_request_size', models.FloatField(default=0)),
                ('validatecertificate_request_size', models.FloatField(default=0)),
                ('validatedocument_request_size', models.FloatField(default=0)),
            ],
            options={
                'verbose_name': 'Resumen de estadística',
                'verbose_name_plural': 'Resumen de estadísticas',
                'ordering': ['-year', '-month'],
            },
        ),
        migrations.AlterModelOptions(
            name='system_request_metric',
            options={'ordering': ['operation_type', 'transaction_status', 'start_decrypt'], 'verbose_name': 'Métrica del sistema', 'verbose_name_plural': 'Métricas del sistema'},
        ),
        migrations.AlterField(
            model_name='system_request_metric',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='institution.institution'),
        ),
        migrations.AddIndex(
            model_name='system_request_metric',
            index=models.Index(fields=['operation_type'], name='corebase_sy_operati_3a5afe_idx'),
        ),
        migrations.AddIndex(
            model_name='system_request_metric',
            index=models.Index(fields=['transaction_status'], name='corebase_sy_transac_111ced_idx'),
        ),
        migrations.AddIndex(
            model_name='system_request_metric',
            index=models.Index(fields=['start_decrypt'], name='corebase_sy_start_d_dbef9a_idx'),
        ),
        migrations.AddIndex(
            model_name='datasummary',
            index=models.Index(fields=['year'], name='corebase_da_year_bb3560_idx'),
        ),
        migrations.AddIndex(
            model_name='datasummary',
            index=models.Index(fields=['month'], name='corebase_da_month_9bbf33_idx'),
        ),
    ]
