# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-08 18:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corebase', '0003_auto_20180809_2110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userconditionsandterms',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserConditionsAndTerms',
        ),
    ]
