# Generated by Django 3.1.11 on 2021-05-22 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corebase', '0004_auto_20210408_0816'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ErrorFound',
        ),
        migrations.DeleteModel(
            name='Signer',
        ),
        migrations.DeleteModel(
            name='WarningReceived',
        ),
    ]
