# Generated by Django 3.1.11 on 2021-05-22 16:21

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='validatepersondocumentrequest',
            name='code',
        ),
        migrations.RemoveField(
            model_name='validatepersondocumentrequest',
            name='errors',
        ),
        migrations.RemoveField(
            model_name='validatepersondocumentrequest',
            name='signers',
        ),
        migrations.RemoveField(
            model_name='validatepersondocumentrequest',
            name='warnings',
        ),
        migrations.AddField(
            model_name='validatepersondocumentrequest',
            name='validation_data',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
    ]
