# Generated by Django 3.0.7 on 2020-06-22 04:23

from django.db import migrations, models
import person.models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='validatepersondocumentdatarequest',
            name='expiration_datetime',
        ),
        migrations.AlterField(
            model_name='authenticatepersondatarequest',
            name='expiration_datetime',
            field=models.DateTimeField(default=person.models.get_default_expiration),
        ),
        migrations.AlterField(
            model_name='signpersondatarequest',
            name='expiration_datetime',
            field=models.DateTimeField(default=person.models.get_default_expiration),
        ),
        migrations.AlterField(
            model_name='validatepersoncertificatedatarequest',
            name='expiration_datetime',
            field=models.DateTimeField(default=person.models.get_default_expiration),
        ),
    ]
