# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-01 22:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='validatepersondocumentdatarequest',
            name='arrived_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='validatepersondocumentdatarequest',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
