# Generated by Django 3.1.11 on 2021-05-22 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_auto_20210522_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='personlogin',
            name='operand',
            field=models.CharField(default='*', max_length=15),
        ),
        migrations.AddField(
            model_name='personlogin',
            name='operatorA',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='personlogin',
            name='operatorB',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='personlogin',
            name='serial',
            field=models.CharField(default='123456', help_text='Serial con el cual se autentica', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='personlogin',
            name='algorithm',
            field=models.CharField(choices=[('sha256', 'sha256'), ('sha384', 'sha384'), ('sha512', 'sha512')], help_text='Debe ser alguno de los siguientes: sha256, sha384, sha512', max_length=7),
        ),
        migrations.AlterField(
            model_name='personlogin',
            name='code',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='personlogin',
            name='data_hash',
            field=models.CharField(help_text='Suma hash de datos de tamaño máximo 130 caracteres, usando el\n                                 algoritmo especificado ', max_length=130, null=True),
        ),
        migrations.AlterField(
            model_name='personlogin',
            name='public_certificate',
            field=models.TextField(help_text='Certificado público  de firma, para firma digital avanzada', null=True),
        ),
    ]
