# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-15 05:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0006_auto_20180916_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='authenticatepersondatarequest',
            name='hash_docsigned',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='signpersondatarequest',
            name='hash_docsigned',
            field=models.SmallIntegerField(default=0),
        ),
    ]
