# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-13 15:59
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import institution.presentation
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('corebase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthenticateDataRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_url', models.URLField()),
                ('identification', models.CharField(help_text="'%Y-%m-%d %H:%M:%S',   es decir  '2006-10-25 14:30:59'", max_length=15, validators=[django.core.validators.RegexValidator('^(\\d{9,11})$', message='Debe contener 9 dígitos o 11 para extranjeros y 10 para cédulas jurídicas por ejemplo: 102340456 para nacionales o 10234045611 para extranjeros')])),
                ('request_datetime', models.DateTimeField()),
                ('code', models.CharField(default='N/D', max_length=20)),
                ('status', models.IntegerField(choices=[(1, 'Solicitud recibida correctamente'), (2, 'Ha ocurrido algún problema al solicitar la firma'), (3, 'Solicitud con campos incompletos'), (4, 'Diferencia de hora no permitida entre cliente y servidor'), (5, 'La entidad no se encuentra registrada'), (6, 'La entidad se encuentra en estado inactiva'), (7, 'La URL no pertenece a la entidad solicitante'), (8, 'El tamaño de hash debe ser entre 1 y 130 caracteres'), (9, 'Algoritmo desconocido'), (10, 'Certificado incorrecto')], default=1)),
                ('status_text', models.CharField(default='n/d', max_length=256)),
                ('sign_document', models.TextField(blank=True, null=True)),
                ('response_datetime', models.DateTimeField(auto_now=True)),
                ('expiration_datetime', models.DateTimeField()),
                ('id_transaction', models.IntegerField(default=0)),
                ('duration', models.SmallIntegerField(default=3)),
                ('received_notification', models.BooleanField(default=False)),
            ],
            options={
                'permissions': (('view_authenticatedatarequest', 'Can see available Authenticate Data Request'),),
                'ordering': ('request_datetime',),
            },
        ),
        migrations.CreateModel(
            name='AuthenticateRequest',
            fields=[
                ('code', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('arrived_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('data_hash', models.CharField(help_text='Suma hash de datos de tamaño máximo 130 caracteres, usando el\n                                 algoritmo especificado ', max_length=130)),
                ('algorithm', models.CharField(choices=[('sha256', 'sha256'), ('sha384', 'sha384'), ('sha512', 'sha512')], help_text=' Debe ser alguno de los siguientes: sha256, sha384, sha512', max_length=7)),
                ('public_certificate', models.TextField(help_text='Certificado público de la institución (ver Institución) ')),
                ('institution', models.CharField(help_text='UUID de la institución', max_length=50)),
                ('data_request', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='institution.AuthenticateDataRequest')),
            ],
            options={
                'permissions': (('view_authenticaterequest', 'Can see available Authenticate Request'),),
                'ordering': ('arrived_time',),
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('name', models.CharField(max_length=250)),
                ('code', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('bccr_bussiness', models.IntegerField(default=1)),
                ('bccr_entity', models.IntegerField(default=1)),
                ('domain', models.CharField(max_length=250)),
                ('institution_unit', models.CharField(default='ND', max_length=250)),
                ('private_key', models.TextField()),
                ('public_key', models.TextField()),
                ('public_certificate', models.TextField()),
                ('server_sign_key', models.TextField()),
                ('server_public_key', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('view_institution', 'Can see available tasks'),),
                'ordering': ('pk',),
            },
            bases=(models.Model, institution.presentation.PEMpresentation),
        ),
        migrations.CreateModel(
            name='NotificationURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250)),
                ('url', models.URLField(blank=True, null=True)),
                ('not_webapp', models.BooleanField(default=False)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institution.Institution')),
            ],
            options={
                'permissions': (('view_notificationurl', 'Can see available notification urls'),),
                'ordering': ('institution',),
            },
        ),
        migrations.CreateModel(
            name='SignDataRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_url', models.URLField()),
                ('identification', models.CharField(help_text="'%Y-%m-%d %H:%M:%S',   es decir  '2006-10-25 14:30:59'", max_length=15, validators=[django.core.validators.RegexValidator('^(\\d{9,11})$', message='Debe contener 9 dígitos o 11 para extranjeros y 10 para cédulas jurídicas por ejemplo: 102340456 para nacionales o 10234045611 para extranjeros')])),
                ('request_datetime', models.DateTimeField()),
                ('code', models.CharField(default='N/D', max_length=20)),
                ('status', models.IntegerField(choices=[(1, 'Solicitud recibida correctamente'), (2, 'Ha ocurrido algún problema al solicitar la firma'), (3, 'Solicitud con campos incompletos'), (4, 'Diferencia de hora no permitida entre cliente y servidor'), (5, 'La entidad no se encuentra registrada'), (6, 'La entidad se encuentra en estado inactiva'), (7, 'La URL no pertenece a la entidad solicitante'), (8, 'El tamaño de hash debe ser entre 1 y 130 caracteres'), (9, 'Algoritmo desconocido'), (10, 'Certificado incorrecto')], default=1)),
                ('status_text', models.CharField(default='n/d', max_length=256)),
                ('response_datetime', models.DateTimeField(auto_now=True)),
                ('expiration_datetime', models.DateTimeField()),
                ('id_transaction', models.IntegerField(default=0)),
                ('sign_document', models.TextField(blank=True, null=True)),
                ('duration', models.SmallIntegerField(default=3)),
                ('received_notification', models.BooleanField(default=False)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institution.Institution')),
            ],
            options={
                'permissions': (('view_signerdatarequest', 'Can see available Signer Data Request'),),
                'ordering': ('request_datetime',),
            },
        ),
        migrations.CreateModel(
            name='SignRequest',
            fields=[
                ('code', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('arrived_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('data_hash', models.CharField(help_text='Suma hash de datos de tamaño máximo 130 caracteres, usando el\n                                 algoritmo especificado ', max_length=130)),
                ('algorithm', models.CharField(choices=[('sha256', 'sha256'), ('sha384', 'sha384'), ('sha512', 'sha512')], help_text=' Debe ser alguno de los siguientes: sha256, sha384, sha512', max_length=7)),
                ('public_certificate', models.TextField(help_text='Certificado público de la institución (ver Institución) ')),
                ('institution', models.CharField(help_text='UUID de la institución', max_length=50)),
                ('data_request', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='institution.SignDataRequest')),
            ],
            options={
                'permissions': (('view_signrequest', 'Can see available Sign Request'),),
                'ordering': ('arrived_time',),
            },
        ),
        migrations.CreateModel(
            name='ValidateCertificateDataRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_url', models.URLField()),
                ('identification', models.CharField(help_text="'%Y-%m-%d %H:%M:%S',   es decir  '2006-10-25 14:30:59'", max_length=15, null=True, validators=[django.core.validators.RegexValidator('^(\\d{9,11})$', message='Debe contener 9 dígitos o 11 para extranjeros y 10 para cédulas jurídicas por ejemplo: 102340456 para nacionales o 10234045611 para extranjeros')])),
                ('request_datetime', models.DateTimeField()),
                ('code', models.CharField(default='N/D', max_length=20)),
                ('status', models.IntegerField(choices=[(1, 'Solicitud recibida correctamente'), (2, 'Ha ocurrido algún problema al solicitar la firma'), (3, 'Solicitud con campos incompletos'), (4, 'Diferencia de hora no permitida entre cliente y servidor'), (5, 'La entidad no se encuentra registrada'), (6, 'La entidad se encuentra en estado inactiva'), (7, 'La URL no pertenece a la entidad solicitante'), (8, 'El tamaño de hash debe ser entre 1 y 130 caracteres'), (9, 'Algoritmo desconocido'), (10, 'Certificado incorrecto')], default=1)),
                ('status_text', models.CharField(default='n/d', max_length=256)),
                ('response_datetime', models.DateTimeField(auto_now=True)),
                ('fue_exitosa', models.BooleanField(default=True)),
                ('nombre_completo', models.CharField(max_length=250, null=True)),
                ('inicio_vigencia', models.DateTimeField(null=True)),
                ('fin_vigencia', models.DateTimeField(null=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institution.Institution')),
            ],
            options={
                'permissions': (('view_validatecertificatedatarequest', 'Can see available validate certificate Data Request'),),
                'ordering': ('request_datetime',),
            },
        ),
        migrations.CreateModel(
            name='ValidateCertificateRequest',
            fields=[
                ('code', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('arrived_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('data_hash', models.CharField(help_text='Suma hash de datos de tamaño máximo 130 caracteres, usando el\n                                 algoritmo especificado ', max_length=130)),
                ('algorithm', models.CharField(choices=[('sha256', 'sha256'), ('sha384', 'sha384'), ('sha512', 'sha512')], help_text=' Debe ser alguno de los siguientes: sha256, sha384, sha512', max_length=7)),
                ('public_certificate', models.TextField(help_text='Certificado público de la institución (ver Institución) ')),
                ('institution', models.CharField(help_text='UUID de la institución', max_length=50)),
                ('data_request', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='institution.ValidateCertificateDataRequest')),
            ],
            options={
                'permissions': (('view_validaterequest', 'Can see available validate certificate Request'),),
                'ordering': ('arrived_time',),
            },
        ),
        migrations.CreateModel(
            name='ValidateDocumentDataRequest',
            fields=[
                ('basedocument_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='corebase.BaseDocument')),
                ('notification_url', models.URLField()),
                ('request_datetime', models.DateTimeField()),
                ('code', models.CharField(default='N/D', max_length=20)),
                ('status', models.IntegerField(choices=[(1, 'Solicitud recibida correctamente'), (2, 'Ha ocurrido algún problema al solicitar la firma'), (3, 'Solicitud con campos incompletos'), (4, 'Diferencia de hora no permitida entre cliente y servidor'), (5, 'La entidad no se encuentra registrada'), (6, 'La entidad se encuentra en estado inactiva'), (7, 'La URL no pertenece a la entidad solicitante'), (8, 'El tamaño de hash debe ser entre 1 y 130 caracteres'), (9, 'Algoritmo desconocido'), (10, 'Certificado incorrecto')], default=1)),
                ('status_text', models.CharField(default='n/d', max_length=256)),
                ('fue_exitosa', models.BooleanField(default=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institution.Institution')),
            ],
            options={
                'permissions': (('view_validatedocumentdatarequest', 'Can see available validate document Data Request'),),
                'ordering': ('request_datetime',),
            },
            bases=('corebase.basedocument',),
        ),
        migrations.CreateModel(
            name='ValidateDocumentRequest',
            fields=[
                ('code', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('arrived_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('data_hash', models.CharField(help_text='Suma hash de datos de tamaño máximo 130 caracteres, usando el\n                                 algoritmo especificado ', max_length=130)),
                ('algorithm', models.CharField(choices=[('sha256', 'sha256'), ('sha384', 'sha384'), ('sha512', 'sha512')], help_text=' Debe ser alguno de los siguientes: sha256, sha384, sha512', max_length=7)),
                ('public_certificate', models.TextField(help_text='Certificado público de la institución (ver Institución) ')),
                ('institution', models.CharField(help_text='UUID de la institución', max_length=50)),
                ('data_request', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='institution.ValidateDocumentDataRequest')),
            ],
            options={
                'permissions': (('view_validatedocumentrequest', 'Can see validate document Sign Request'),),
                'ordering': ('arrived_time',),
            },
        ),
        migrations.AddField(
            model_name='authenticatedatarequest',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institution.Institution'),
        ),
    ]
