# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-15 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0003_notificationurl_is_demo'),
    ]

    operations = [
        migrations.AddField(
            model_name='validatedocumentrequest',
            name='format',
            field=models.CharField(choices=[('cofirma', 'CoFirma'), ('contrafirma', 'ContraFirma'), ('msoffice', 'MS Office'), ('odf', 'Open Document Format')], default='n/d', max_length=15),
        ),
        migrations.AlterField(
            model_name='authenticatedatarequest',
            name='id_transaction',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='signdatarequest',
            name='id_transaction',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
