# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-03 05:58
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0005_auto_20171116_0042'),
    ]

    operations = [
        migrations.AddField(
            model_name='authenticaterequest',
            name='encrypt_method',
            field=models.CharField(blank=True, choices=[('aes_eax', 'aes_eax (recomendado)'), ('aes-256-cfb', 'aes-256-cfb')], default='aes_eax', max_length=25),
        ),
        migrations.AddField(
            model_name='signrequest',
            name='encrypt_method',
            field=models.CharField(blank=True, choices=[('aes_eax', 'aes_eax (recomendado)'), ('aes-256-cfb', 'aes-256-cfb')], default='aes_eax', max_length=25),
        ),
        migrations.AddField(
            model_name='validatecertificaterequest',
            name='encrypt_method',
            field=models.CharField(blank=True, choices=[('aes_eax', 'aes_eax (recomendado)'), ('aes-256-cfb', 'aes-256-cfb')], default='aes_eax', max_length=25),
        ),
        migrations.AddField(
            model_name='validatedocumentrequest',
            name='encrypt_method',
            field=models.CharField(blank=True, choices=[('aes_eax', 'aes_eax (recomendado)'), ('aes-256-cfb', 'aes-256-cfb')], default='aes_eax', max_length=25),
        ),
        migrations.AlterField(
            model_name='authenticatedatarequest',
            name='identification',
            field=models.CharField(help_text="'%Y-%m-%d %H:%M:%S',   es decir  '2006-10-25 14:30:59'", max_length=15, validators=[django.core.validators.RegexValidator('"(^[1|5]\\d{11}$)|(^\\d{2}-\\d{4}-\\d{4}$)"', message='Debe tener el formato 08-8888-8888 para nacionales o 500000000000 o 100000000000')]),
        ),
        migrations.AlterField(
            model_name='signdatarequest',
            name='identification',
            field=models.CharField(help_text="'%Y-%m-%d %H:%M:%S',   es decir  '2006-10-25 14:30:59'", max_length=15, validators=[django.core.validators.RegexValidator('"(^[1|5]\\d{11}$)|(^\\d{2}-\\d{4}-\\d{4}$)"', message='Debe tener el formato 08-8888-8888 para nacionales o 500000000000 o 100000000000')]),
        ),
        migrations.AlterField(
            model_name='validatecertificatedatarequest',
            name='identification',
            field=models.CharField(help_text="'%Y-%m-%d %H:%M:%S',   es decir  '2006-10-25 14:30:59'", max_length=15, null=True, validators=[django.core.validators.RegexValidator('"(^[1|5]\\d{11}$)|(^\\d{2}-\\d{4}-\\d{4}$)"', message='Debe tener el formato 08-8888-8888 para nacionales o 500000000000 o 100000000000')]),
        ),
        migrations.AlterField(
            model_name='validatedocumentdatarequest',
            name='format',
            field=models.CharField(choices=[('cofirma', 'CoFirma'), ('contrafirma', 'ContraFirma'), ('msoffice', 'MS Office'), ('odf', 'Open Document Format'), ('pdf', 'PDF')], default='n/d', max_length=15),
        ),
    ]
