# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-17 01:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0007_auto_20180616_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authenticatedatarequest',
            name='institution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='institution.Institution'),
        ),
    ]
