# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-17 05:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0007_auto_20180616_0722'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='administrative_institution',
            field=models.BooleanField(default=False),
        ),
    ]
