# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-17 05:44
from __future__ import unicode_literals

from django.db import migrations
from django.contrib.auth.hashers import make_password


def create_default_templates(apps, schema_editor):
    Institution = apps.get_model(
        'institution', 'Institution')

    User = apps.get_registered_model('auth', 'User')

    admin = User(
        username='dfva',
        email='dfva@dfva.info',
        password=make_password('admin12345'),
        is_superuser=True,
        is_staff=True
    )
    admin.save()
    print("""
    
    ATENCION: SE ha creado un usuario administrador con los siguientes datos:
    username: dfva
    password: admin12345
    
    Cambielo inmediatamente.
    
    """)

    inst = Institution(
        user=admin,
        name="DFVA admin institution (no eliminar)",
        domain="dfva.info",
        email="info@dfva.info",
        phone="8888888",
        administrative_institution=True
    )
    inst.save()


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0008_institution_administrative_institution'),
    ]

    operations = [
        migrations.RunPython(create_default_templates),
    ]
