# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-17 03:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0011_auto_20180809_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authenticaterequest',
            name='algorithm',
            field=models.CharField(choices=[('sha256', 'sha256'), ('sha384', 'sha384'), ('sha512', 'sha512')], help_text='Debe ser alguno de los siguientes: sha256, sha384, sha512', max_length=7),
        ),
        migrations.AlterField(
            model_name='signrequest',
            name='algorithm',
            field=models.CharField(choices=[('sha256', 'sha256'), ('sha384', 'sha384'), ('sha512', 'sha512')], help_text='Debe ser alguno de los siguientes: sha256, sha384, sha512', max_length=7),
        ),
        migrations.AlterField(
            model_name='validatecertificaterequest',
            name='algorithm',
            field=models.CharField(choices=[('sha256', 'sha256'), ('sha384', 'sha384'), ('sha512', 'sha512')], help_text='Debe ser alguno de los siguientes: sha256, sha384, sha512', max_length=7),
        ),
        migrations.AlterField(
            model_name='validatedocumentrequest',
            name='algorithm',
            field=models.CharField(choices=[('sha256', 'sha256'), ('sha384', 'sha384'), ('sha512', 'sha512')], help_text='Debe ser alguno de los siguientes: sha256, sha384, sha512', max_length=7),
        ),
    ]
