# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-02 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0012_auto_20180916_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='signdatarequest',
            name='place',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='signdatarequest',
            name='reason',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='authenticatedatarequest',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='signdatarequest',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
