# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-03 07:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0013_auto_20181102_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authenticatedatarequest',
            name='status',
            field=models.IntegerField(choices=[(0, 'Solicitud recibida correctamente.'), (1, 'Ha ocurrido algún problema al solicitar la firma o autenticación.'), (2, 'Solicitud con campos incompletos.'), (3, 'Existe una diferencia no permitida entre la fecha y hora del cliente y la del servidor. La fecha/hora de la solicitud no debe tener una diferencia de más de 60 segundos de la fecha/hora del servidor.'), (4, 'La entidad no se encuentra registrada.'), (5, 'La entidad se encuentra en estado inactiva.'), (6, 'El negocio no pertenece a la entidad solicitante.'), (7, 'El tamaño del resumen de la solicitud de firma es no valido, este debe ser mayor a 1 y menor a  250 caracteres.'), (8, 'El tamaño de la razón de firma de la solicitud de firma PAdES es inválida, este debe ser mayor a 1 y menor a  125 caracteres.'), (9, 'El suscriptor se encuentra desconectado para recibir una solicitud.'), (10, 'El formato de la identificación enviado no es válido, este debe tener un formato para un nacional 0#-####-#### para un DIDI 5########### para un DIMEX 1###########')], default=0),
        ),
        migrations.AlterField(
            model_name='signdatarequest',
            name='status',
            field=models.IntegerField(choices=[(0, 'Solicitud recibida correctamente.'), (1, 'Ha ocurrido algún problema al solicitar la firma o autenticación.'), (2, 'Solicitud con campos incompletos.'), (3, 'Existe una diferencia no permitida entre la fecha y hora del cliente y la del servidor. La fecha/hora de la solicitud no debe tener una diferencia de más de 60 segundos de la fecha/hora del servidor.'), (4, 'La entidad no se encuentra registrada.'), (5, 'La entidad se encuentra en estado inactiva.'), (6, 'El negocio no pertenece a la entidad solicitante.'), (7, 'El tamaño del resumen de la solicitud de firma es no valido, este debe ser mayor a 1 y menor a  250 caracteres.'), (8, 'El tamaño de la razón de firma de la solicitud de firma PAdES es inválida, este debe ser mayor a 1 y menor a  125 caracteres.'), (9, 'El suscriptor se encuentra desconectado para recibir una solicitud.'), (10, 'El formato de la identificación enviado no es válido, este debe tener un formato para un nacional 0#-####-#### para un DIDI 5########### para un DIMEX 1###########')], default=0),
        ),
        migrations.AlterField(
            model_name='validatecertificatedatarequest',
            name='status',
            field=models.IntegerField(choices=[(0, 'Certificado válido.'), (1, 'Error interno al validar el certificado.'), (2, 'Los bytes enviados no corresponden a  un certificado.'), (3, 'El certificado del suscriptor está vencido.'), (4, 'El certificado del suscriptor está revocado.'), (5, 'El Certificado enviado no es de confianza porque no es emitido  por la CA Raíz Nacional.'), (6, 'El certificado enviado no es de autenticación.'), (7, 'El certificado tiene un problema de estructura, no cuenta con el oid  de ocsp en el que se encuentra la dirección del servicio.'), (8, 'El certificado tiene un problema de estructura, no cuenta con los usos de la clave necesarios para un certificado de autenticación.'), (9, 'El certificado tiene un problema de estructura, el campo  CN del sujeto tiene una estructura inválida.'), (10, 'El certificado tiene un problema de estructura, el campo  SERIALNUMBER del sujeto tiene una estructura inválida.'), (11, 'La entidad no se encuentra registrada.'), (12, 'La entidad no se encuentra en estado inactiva.')], default=0),
        ),
        migrations.AlterField(
            model_name='validatedocumentdatarequest',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
