# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-13 15:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institution', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autenticar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institution.NotificationURL')),
            ],
        ),
    ]
