# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 00:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('corebase', '0003_auto_20170719_0547'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autenticar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corebase.NotificationURL')),
            ],
        ),
    ]
